modLoader="javafml"
loaderVersion="[40,)"
license="Academic Free License v3.0"

[[mods]]
modId="siriusr"
version="1.0.0"
displayName="ExtraMusic"
credits="EarthBlock Studios"
displayURL="https://magosiriusgameplays.wordpress.com/"
logoFile="logo.png"
authors="Magosirius"

[[dependencies.siriusr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="NONE"
    side="BOTH"




